import type { Config } from "tailwindcss"

const config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      safelist: [
        "bg-blue-50",
        "bg-blue-100",
        "bg-blue-500",
        "text-blue-500",
        "text-blue-600",
        "text-blue-700",
        "text-blue-800",
        "bg-green-50",
        "bg-green-100",
        "bg-green-500",
        "text-green-500",
        "text-green-600",
        "text-green-700",
        "text-green-800",
        "bg-purple-50",
        "bg-purple-100",
        "bg-purple-500",
        "text-purple-500",
        "text-purple-600",
        "text-purple-700",
        "text-purple-800",
        "bg-amber-50",
        "bg-amber-100",
        "bg-amber-500",
        "text-amber-500",
        "text-amber-600",
        "text-amber-700",
        "text-amber-800",
        "bg-red-50",
        "bg-red-100",
        "bg-red-500",
        "text-red-500",
        "text-red-600",
        "text-red-700",
        "text-red-800",
        "bg-teal-50",
        "bg-teal-100",
        "bg-teal-500",
        "text-teal-500",
        "text-teal-600",
        "text-teal-700",
        "text-teal-800",
        "bg-pink-50",
        "bg-pink-100",
        "bg-pink-500",
        "text-pink-500",
        "text-pink-600",
        "text-pink-700",
        "text-pink-800",
        "bg-indigo-50",
        "bg-indigo-100",
        "bg-indigo-500",
        "text-indigo-500",
        "text-indigo-600",
        "text-indigo-700",
        "text-indigo-800",
        "bg-orange-50",
        "bg-orange-100",
        "bg-orange-500",
        "text-orange-500",
        "text-orange-600",
        "text-orange-700",
        "text-orange-800",
      ],
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config
